### ISSUE TITLE
Team37a links broken

### ISSUE THREAD

**Issue by chrismattmann** [USCDataScience/polar.usc.edu#18]
If you visit Team37a the links for Polar Bear Distribution are broken (when you click show a different view):

http://polar.usc.edu/html/Team37SiteA1.html

**Comment by titusjung** [comment]
I fixed it so it matches the original behavior. The link should point to Team37a1.html.
However, I feel the link might be redundant. Team37a1 is the doughnut example that is right next to Team37a in the other-examples page. It might be better to just remove the link.

**Comment by chrismattmann** [comment]
@titusjung i'm fine either way to make it - we should just be consistent. Your call on how to resolve it. Either no link; or link that actually works :)

**Comment by chrismattmann** [comment]
link still broken (use lowercase "team" and not "Team")

http://irds.usc.edu/polar.usc.edu/html/team37a1.html

Not

http://irds.usc.edu/polar.usc.edu/html/Team37a1.html

**Comment by titusjung** [comment]
Fixed the typo
